### ISSUE TITLE
[Incoming offer] Tooltip shows then quickly disappear on mouse hover

### ISSUE THREAD

**Issue by nomis51** [nomis51/Menagerie#41]

**Comment by javiergarber** [comment]
2022-09-01 01:15:36.008 +02:00 [INF] Initializing data services...
2022-09-01 01:15:36.023 +02:00 [INF] Unexpected process cleaned PID 35932 C:\Users\javie\AppData\Local\Menagerie\Menagerie.exe
2022-09-01 01:15:36.197 +02:00 [INF] Starting data services...
2022-09-01 01:15:36.198 +02:00 [WRN] Application starting Application Version: 2.1.4 bc58e996-bfda-4d3b-b2ce-6edd5eb50ad7
2022-09-01 01:15:36.260 +02:00 [INF] Trying to get 64bits location
2022-09-01 01:15:36.261 +02:00 [INF] PoE location D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\PathOfExileSteam.exe
2022-09-01 01:15:36.261 +02:00 [INF] 64bits Client file location: D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\logs\Client.txt
2022-09-01 01:15:37.072 +02:00 [INF] Loading item categories images...
2022-09-01 01:31:49.129 +02:00 [INF] Image divine doesn't exists, downloading it from https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lNb2RWYWx1ZXMiLCJzY2FsZSI6MX1d/ec48896769/CurrencyModValues.png...
2022-09-01 01:53:51.521 +02:00 [INF] Trying to get 64bits location
2022-09-01 01:53:51.521 +02:00 [INF] PoE location D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\PathOfExileSteam.exe
2022-09-01 01:53:51.522 +02:00 [INF] 64bits Client file location: D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\logs\Client.txt
2022-09-01 02:07:53.685 +02:00 [WRN] Unable to write to database trades: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"3ae24bd4-7490-4a72-8763-0d90d4fa6976"'..    at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Menagerie.Data.Providers.DatabaseProvider.Insert[T](String collectionName, T data)
2022-09-01 13:34:21.507 +02:00 [INF] Initializing data services...
2022-09-01 13:34:21.519 +02:00 [INF] Unexpected process cleaned PID 45080 C:\Users\javie\AppData\Local\Menagerie\Menagerie.exe
2022-09-01 13:34:21.648 +02:00 [INF] Starting data services...
2022-09-01 13:34:21.649 +02:00 [WRN] Application starting Application Version: 2.1.4 bc58e996-bfda-4d3b-b2ce-6edd5eb50ad7
2022-09-01 13:34:22.207 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:22.447 +02:00 [INF] Loading item categories images...
2022-09-01 13:34:22.728 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:23.253 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:23.780 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:24.290 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:24.802 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:25.315 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:25.830 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:26.349 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:26.862 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:27.372 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:27.883 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:28.396 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:28.909 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:29.420 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:29.931 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:30.445 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:30.957 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:31.470 +02:00 [WRN] Unable to show/hide overlay: Acceso denegado.    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Menagerie.Data.Services.GameWindowService.<AutoHideOverlay>b__14_0()
2022-09-01 13:34:31.752 +02:00 [INF] Trying to get 64bits location
2022-09-01 13:34:31.752 +02:00 [INF] PoE location D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\PathOfExileSteam.exe
2022-09-01 13:34:31.753 +02:00 [INF] 64bits Client file location: D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\logs\Client.txt
2022-09-01 14:26:57.816 +02:00 [INF] Trying to get 64bits location
2022-09-01 14:26:57.818 +02:00 [INF] PoE location D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\PathOfExileSteam.exe
2022-09-01 14:26:57.819 +02:00 [INF] 64bits Client file location: D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\logs\Client.txt
2022-09-01 14:49:00.506 +02:00 [WRN] Unable to write to database trades: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"6fb712e3-3255-41fa-9159-eaa83448e58a"'..    at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Menagerie.Data.Providers.DatabaseProvider.Insert[T](String collectionName, T data)

**Comment by javiergarber** [comment]
2022-09-01 01:15:36.008 +02:00 [INF] Initializing data services...
2022-09-01 01:15:36.023 +02:00 [INF] Unexpected process cleaned PID 35932 C:\Users\javie\AppData\Local\Menagerie\Menagerie.exe
2022-09-01 01:15:36.197 +02:00 [INF] Starting data services...
2022-09-01 01:15:36.198 +02:00 [WRN] Application starting Application Version: 2.1.4 bc58e996-bfda-4d3b-b2ce-6edd5eb50ad7
2022-09-01 01:15:36.260 +02:00 [INF] Trying to get 64bits location
2022-09-01 01:15:36.261 +02:00 [INF] PoE location D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\PathOfExileSteam.exe
2022-09-01 01:15:36.261 +02:00 [INF] 64bits Client file location: D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\logs\Client.txt
2022-09-01 01:15:37.072 +02:00 [INF] Loading item categories images...
2022-09-01 01:31:49.129 +02:00 [INF] Image divine doesn't exists, downloading it from https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lNb2RWYWx1ZXMiLCJzY2FsZSI6MX1d/ec48896769/CurrencyModValues.png...
2022-09-01 01:53:51.521 +02:00 [INF] Trying to get 64bits location
2022-09-01 01:53:51.521 +02:00 [INF] PoE location D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\PathOfExileSteam.exe
2022-09-01 01:53:51.522 +02:00 [INF] 64bits Client file location: D:\Juegos\SteamLibrary\steamapps\common\Path of Exile\logs\Client.txt
2022-09-01 02:07:53.685 +02:00 [WRN] Unable to write to database trades: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"3ae24bd4-7490-4a72-8763-0d90d4fa6976"'..    at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Menagerie.Data.Providers.DatabaseProvider.Insert[T](String collectionName, T data)

**Comment by javiergarber** [comment]
Those are the logs from yesterday, last time I tested that
